module.exports = {
  presets: ['module:@react-native/babel-preset'],
  plugins: [
    [
      'module-resolver',
      {
        root: ['./src'],
        alias: {
          assets: './src/assets',
          components: './src/components',
          configs: './src/configs',
          hooks: './src/hooks',
          router: './src/router',
          helpers: './src/helpers',
          screens: './src/screens',
          services: './src/services',
          store: './src/store',
          theme: './src/theme',
          types: './src/types',
          constants: './src/constants',
          utils: './src/utils',
          core: './src/core',
          localization: './src/localization',
          devtools: './src/devtools',
          hocs: './src/hocs',
          mocks: './src/mocks',
          stacks: './src/stacks',
          container: './src/container',
          animations: './src/animations',
          reducers: './src/reducers',
        },
      },
    ],
  ],
};
